server {
    listen 80;
    listen [::]:80;
    server_name ski.mccarrison.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ski.mccarrison.me;

    # ssl_certificate     /etc/letsencrypt/live/ski.mccarrison.me/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/ski.mccarrison.me/privkey.pem;

    root /var/www/skifree-web;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(js|css|html)$ {
        add_header Cache-Control "no-cache";
    }
}
